name: Launcher Build

on:
  workflow_dispatch: # Ejecutar manualmente desde GitHub
  push:
    branches: [ master ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_tag
        run: |
          TAG=$(jq -r .version package.json)
          echo "tag=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: Release ${{ env.tag }}
          draft: false
          prerelease: ${{ contains(env.tag, 'beta') || contains(env.tag, 'alpha') }}
          allowUpdates: true

  build-launcher:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Build for current OS
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          case "$RUNNER_OS" in
            Linux)
              npx electron-builder --linux
              ;;
            Windows)
              npx electron-builder --win
              ;;
            macOS)
              npx electron-builder --mac
              ;;
          esac

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.release_tag }}
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
